import express from 'express';
import { createProduct, deleteProduct, getAProduct, getProduct, updateProduct } from '../controller/ProductController.js';
import { validateProduct, validateUpdateProduct } from '../middlewares/validator.middleware.js';
const productRoute = express.Router();
productRoute.post("/create",validateProduct,createProduct);
productRoute.get('/get',getProduct);
productRoute.get('/get/:id',getAProduct);
productRoute.put('/update/:id',validateUpdateProduct,updateProduct);
productRoute.delete('/delete/:id',deleteProduct);
export default productRoute;